# Generated by Django 2.2.13 on 2020-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20200831_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(editable=False, max_length=6, null=True, verbose_name='Código'),
        ),
    ]
