# Generated by Django 2.2.13 on 2020-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20201110_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('F', 'FINALIZADO')], max_length=1, verbose_name='Status'),
        ),
    ]
