# Generated by Django 2.2.13 on 2020-11-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20201110_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Dinheiro'), (2, 'Credito'), (3, 'Debito'), (4, 'Carnê')], null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
