# Generated by Django 2.2.13 on 2020-11-11 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0006_auto_20201110_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='caixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprador', to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.PositiveIntegerField(choices=[(1, 'Dinheiro'), (2, 'Credito'), (3, 'Debito'), (4, 'Carnê')], verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
