# Generated by Django 2.2.13 on 2020-11-11 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20201110_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixa', to=settings.AUTH_USER_MODEL),
        ),
    ]
