# Generated by Django 2.2.13 on 2020-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20200806_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VENDEDOR'), (2, 'CAIXA'), (3, 'ADMINISTRADOR')], default=1, verbose_name='Tipo de Usuário'),
        ),
    ]
