# Generated by Django 2.2.13 on 2020-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_auto_20200801_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ATIVO'), (2, 'SPC'), (3, 'SUSPENSO')], default=1),
        ),
    ]
